"""
Django settings for MainWebUIProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv('DEBUG') == 'True'
DEBUG = True

hosts = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,[::1],194.87.214.67,192.168.100.196',  # добавь сюда свой реальный IP
)
ALLOWED_HOSTS = hosts.split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://194.87.214.67:443',  # если кто-то придёт на 443
    'https://194.87.214.67:8443',  # добавляем порт туннеля
    'https://localhost',
    'https://127.0.0.1',
    'https://192.168.100.196',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'WebUiProject.apps.WebUiProjectConfig',
    'WebUIProjectGreenZabGU.apps.WebuiprojectgreenzabguConfig',
    'imagekit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MainWebUIProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'WebUIProjectGreenZabGU.context_processors.eco_balance',  # Теперь в любом HTML шаблоне вы можете писать: {{ user_eco_balance }} ECO.
            ],
        },
    },
]

WSGI_APPLICATION = 'MainWebUIProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_db',
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST', 'db'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/profile/"  # куда по умолчанию идёт после успешного логина
LOGOUT_REDIRECT_URL = "/login/"

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Место, куда собираются все статические файлы для деплоя
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Папки, где будут искаться статические файлы
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'  # URL для доступа к загружаемым файлам

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Путь для хранения файлов

MEDIAFILES_DIRS = [
    os.path.join(BASE_DIR, 'media'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# Docker internal network URL (имя сервиса из docker-compose)
ANYTHINGLLM_API_URL = 'http://192.168.100.185:3001'
ANYTHINGLLM_WORKSPACE = 'expert001'  # Слаг твоего воркспейса
ANYTHINGLLM_API_KEY = 'FH2T4W6-4NNMA2Y-K9X3SDW-HWG7FJN'  # Твой API ключ из настроек AnythingLLM
