FROM lscr.io/linuxserver/webtop:ubuntu-xfce

# Устанавливаем Blender
RUN apt-get update && \
    apt-get install -y blender nvidia-cuda-toolkit && \
    rm -rf /var/lib/apt/lists/*

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

ENV LIBGL_ALWAYS_SOFTWARE=0

ENV TITLE="Blender Workspace"
# ENV PASSWORD="password" # Можно задать пароль, если нужно

