# Generated by Django 5.1.4 on 2026-04-21 19:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Текущий баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кошелек эко-коинов',
                'verbose_name_plural': 'Кошельки эко-коинов',
            },
        ),
        migrations.CreateModel(
            name='EcoCoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Сумма (со знаком)')),
                ('tx_type', models.CharField(choices=[('project_created', 'Создание проекта'), ('blog_published', 'Публикация статьи'), ('daily_bonus', 'Ежедневный бонус'), ('manual_reward', 'Ручное начисление (админом)'), ('shop_purchase', 'Покупка в магазине'), ('transfer_out', 'Перевод другому'), ('transfer_in', 'Перевод от другого')], max_length=30, verbose_name='Тип операции')),
                ('external_id', models.CharField(blank=True, help_text="Например: 'blog:15' или 'project:42'", max_length=255, null=True, verbose_name='ID связанной сущности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='WebUiProject.ecowallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Транзакция эко-коинов',
                'verbose_name_plural': 'Транзакции эко-коинов',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('wallet', 'tx_type', 'external_id'), name='unique_eco_transaction_for_entity')],
            },
        ),
    ]
