# Generated by Django 5.1.4 on 2026-04-21 20:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0002_ecowallet_ecocointransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('reward', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=20, verbose_name='Награда (ECO)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Эко-задание',
                'verbose_name_plural': 'Эко-задания',
            },
        ),
        migrations.CreateModel(
            name='UserTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='WebUiProject.ecotask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
