# Generated by Django 5.1.4 on 2025-09-22 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0002_alter_project_options_alter_project_image_blog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Изображение новости', 'verbose_name_plural': 'Изображения Новостей'},
        ),
        migrations.AlterField(
            model_name='project',
            name='leaders',
            field=models.ManyToManyField(limit_choices_to=models.Q(('groups__name', 'Руководители')), related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(limit_choices_to=models.Q(('groups__name', 'Участники')), related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
