# Generated by Django 5.1.4 on 2026-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0003_ecotask_usertaskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocointransaction',
            name='tx_type',
            field=models.CharField(choices=[('project_created', 'Создание проекта'), ('blog_published', 'Публикация статьи'), ('daily_bonus', 'Ежедневный бонус'), ('manual_reward', 'Ручное начисление (админом)'), ('shop_purchase', 'Покупка в магазине'), ('transfer_out', 'Перевод другому'), ('transfer_in', 'Перевод от другого'), ('task_completed', 'Выполнение эко-задачи')], max_length=30, verbose_name='Тип операции'),
        ),
    ]
