# Generated by Django 5.1.4 on 2026-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0004_alter_ecocointransaction_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocointransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Сумма (целое число)'),
        ),
        migrations.AlterField(
            model_name='ecotask',
            name='reward',
            field=models.IntegerField(default=10, verbose_name='Награда (ECO)'),
        ),
        migrations.AlterField(
            model_name='ecowallet',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Текущий баланс'),
        ),
    ]
