# Generated by Django 5.1.4 on 2026-04-21 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0005_alter_ecocointransaction_amount_alter_ecotask_reward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoHabitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.CharField(default='bi-recycle', help_text='Например: bi-droplet, bi-lightning-charge', max_length=50, verbose_name='CSS класс иконки Bootstrap')),
            ],
            options={
                'verbose_name': 'Категория привычки',
                'verbose_name_plural': 'Категории привычек',
            },
        ),
        migrations.CreateModel(
            name='EcoHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название привычки')),
                ('description', models.TextField(verbose_name='Что нужно сделать')),
                ('base_reward', models.IntegerField(default=5, verbose_name='Базовая награда (ECO)')),
                ('streak_bonus', models.IntegerField(default=1, help_text='+1 ECO за каждый день подряд', verbose_name='Бонус за день серии')),
                ('max_bonus', models.IntegerField(default=15, help_text='Лимит бонуса (чтобы не раздуть экономику)', verbose_name='Максимальный бонус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='WebUiProject.ecohabitcategory')),
            ],
            options={
                'verbose_name': 'Эко-привычка',
                'verbose_name_plural': 'Эко-привычки',
            },
        ),
        migrations.CreateModel(
            name='UserHabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(verbose_name='Дата выполнения')),
                ('streak_count', models.IntegerField(default=1, verbose_name='Длина серии в этот день')),
                ('reward_earned', models.IntegerField(verbose_name='Начислено монет')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='WebUiProject.ecohabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог привычки',
                'verbose_name_plural': 'Логи привычек',
                'ordering': ['-date_completed'],
                'unique_together': {('user', 'habit', 'date_completed')},
            },
        ),
    ]
