# Generated by Django 5.1.4 on 2026-05-20 23:18

import WebUiProject.models
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0009_eventcategory_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код типа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип проверки задания',
                'verbose_name_plural': 'Типы проверок заданий',
            },
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='proof_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=WebUiProject.models.task_proof_image_upload_to, verbose_name='Фотография доказательства'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='proof_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Введенный код/текст'),
        ),
        migrations.AddField(
            model_name='ecotask',
            name='task_type',
            field=models.ForeignKey(help_text='Определяет, что нужно сделать пользователю для выполнения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebUiProject.ecotasktype', verbose_name='Способ проверки'),
        ),
    ]
