# Generated by Django 5.1.4 on 2026-05-20 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0010_ecotasktype_usertaskcompletion_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecotask',
            name='secret_code',
            field=models.CharField(blank=True, help_text='Если заполнено, пользователь должен ввести ровно этот код. Сравнение без учета регистра.', max_length=50, verbose_name="Секретный код (если тип 'Ввод текста')"),
        ),
        migrations.AlterField(
            model_name='ecotask',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebUiProject.ecotasktype', verbose_name='Способ проверки'),
        ),
    ]
