# Generated by Django 5.1.4 on 2026-05-21 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0011_ecotask_secret_code_alter_ecotask_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskcompletion',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено админом')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ecocointransaction',
            name='tx_type',
            field=models.CharField(choices=[('project_created', 'Создание проекта'), ('blog_published', 'Публикация статьи'), ('daily_bonus', 'Ежедневный бонус'), ('manual_reward', 'Ручное начисление (админом)'), ('shop_purchase', 'Покупка в магазине'), ('task_reversed', 'Отмена эко-задачи (списание)'), ('transfer_out', 'Перевод другому'), ('transfer_in', 'Перевод от другого'), ('task_completed', 'Выполнение эко-задачи'), ('habit_tracked', 'Отметка эко-привычки')], max_length=30, verbose_name='Тип операции'),
        ),
        migrations.AddConstraint(
            model_name='usertaskcompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'task'), name='unique_active_task_completion'),
        ),
    ]
