# Generated by Django 5.1.4 on 2026-05-21 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0013_profile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнера')),
                ('icon', models.CharField(default='store', max_length=50, verbose_name='Иконка Material Icons')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название оффера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_in_eco', models.IntegerField(verbose_name='Цена в ECO-коинах')),
                ('category', models.CharField(choices=[('Еда', 'Food'), ('Магазины', 'Shops'), ('Услуги', 'Services'), ('Мерч', 'Merch')], max_length=50, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='WebUiProject.partner')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения маркетплейса',
            },
        ),
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код промокода')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_codes', to='WebUiProject.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Промокод пользователя',
                'verbose_name_plural': 'Промокоды пользователей',
            },
        ),
    ]
