# Generated by Django 5.1.4 on 2026-05-22 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0014_partner_offer_userpromocode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Дата начала партнерства')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUiProject.partner', verbose_name='Бизнес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль партнера',
                'verbose_name_plural': 'Профили партнеров',
            },
        ),
    ]
