# Generated by Django 5.1.4 on 2026-05-26 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiProject', '0015_partnerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partner', to=settings.AUTH_USER_MODEL, verbose_name='Управляющий аккаунт'),
        ),
        migrations.DeleteModel(
            name='PartnerProfile',
        ),
    ]
